language: ruby
os: linux
dist: bionic

arch:
  - amd64
  - arm64

jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx-ucl p7zip
